# -*- coding: utf-8 -*-
"""FakeNewsDetection_app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ux1lgEI8DosRp3s9N751CM0hsN8j6jwP
"""

import streamlit as st
import re
import string
import pickle
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords

# --- Stopwords ---
stop_words = set(stopwords.words('english'))

# --- Preprocessing function ---
def clean_text(text):
    text = text.lower()
    text = re.sub(r'\d+', '', text)
    text = "".join([char for char in text if char not in string.punctuation])
    text = re.sub(r'[^\x00-\x7F]+', '', text)
    words = text.split()
    words = [word for word in words if word not in stop_words and len(word) > 2]
    text = " ".join(words)
    text = re.sub(r'\s+', ' ', text).strip()
    return text

# --- Load models and vectorizer from GitHub folder ---
save_path = 'Models/'  # Folder in your GitHub repo
with open(save_path + 'lr_model.pkl', 'rb') as f:
    lr_model = pickle.load(f)

with open(save_path + 'svm_model.pkl', 'rb') as f:
    svm_model = pickle.load(f)

with open(save_path + 'vectorizer.pkl', 'rb') as f:
    vectorizer = pickle.load(f)

# --- Streamlit UI ---
st.title("Fake News Detection App")

user_input = st.text_area("Enter news article text:")

model_choice = st.selectbox("Choose Model:", ["Logistic Regression", "SVM (LinearSVC)"])

if st.button("Predict"):
    if user_input.strip() == "":
        st.warning("Please enter some text to predict.")
    else:
        # Clean and vectorize
        cleaned_input = clean_text(user_input)
        vectorized_input = vectorizer.transform([cleaned_input])

        # Predict
        if model_choice == "Logistic Regression":
            prediction = lr_model.predict(vectorized_input)[0]
        else:
            prediction = svm_model.predict(vectorized_input)[0]

        st.success(f"The news is predicted as: {'Fake' if prediction==1 else 'Real'}")